# Generated by Django 2.1.3 on 2018-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='simple',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
