# Generated by Django 2.1.3 on 2018-11-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogspost_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='Author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
